### PR TITLE
rename categories

### PR DESCRIPTION
**Pull request by varffs**

### CODE REVIEW

**Comment by mixcas** [comment]
theres still classes that uses old cat names, like `.single-tv-related-tv`. What about those?

**Comment by mixcas** [comment]
`/api/page-data-tv.php` uses:
`'category_name'    => 'tv'`

**Comment by varffs** [comment]
yh should rename classes. and I didnt even realise the API old files were in the repo!

**Comment by mixcas** [comment]
@varffs me either till now :P

**Comment by mixcas** [comment]
@varffs what about migrating the content? it just need to rename in the edit category page, right?

**Comment by varffs** [comment]
yh that does all you need to do

**Comment by mixcas** [comment]
Look, these are the results of `grep -ri 'wire' . | grep -v node_modules | grep -v CMB2`:

```
./css/site.styl:  // WIRE
./css/site.styl:#single-wire-photo-caption
./front-page.php:  <section id="home-wire-posts" class="container margin-bottom-large">
./front-page.php:        $latest_wire = new WP_Query(array(
./front-page.php:        if ($latest_wire->have_posts()) {
./front-page.php:          while ($latest_wire->have_posts()) {
./front-page.php:            $latest_wire->the_post();
./front-page.php:              get_template_part('partials/post-layouts/home-wire-post-col6');
./lib/meta-boxes.php:  // Wire
./lib/meta-boxes.php:  $wire_metabox = new_cmb2_box( array (
./lib/meta-boxes.php:    'id'         => 'wire_metabox',
./lib/meta-boxes.php:    'title'      => __( 'Wire Meta', 'cmb' ),
./lib/meta-boxes.php:  $wire_metabox->add_field( array(
./lib/meta-boxes.php:  $wire_metabox->add_field( array(
./lib/thumbnail-sizes.php:  add_image_size( 'col24-wire-crop', 1304, 400, true );
./partials/scripts.php:    if (is_single() && in_category('Wire')) {
./partials/scripts.php:    <script type="text/javascript">(function k(){window.$SendToKindle&&window.$SendToKindle.Widget?$SendToKindle.Widget.init({"content":"#single-wire-copy","title":"#single-wire-title","author":"#single-wire-author","published":"#single-wire-publication-date"}):setTimeout(k,500);})();</script>
./partials/singles/single-post-article.php:  $category_id = get_cat_ID('Wire');
./partials/singles/single-post-article.php:    <h4><a href="<?php echo $category_link; ?>">Wire</a></h4>
./partials/singles/single-post-article.php:    <?php the_post_thumbnail('col24-wire-crop'); ?>
./partials/singles/single-post-article.php:    <div id="single-wire-photo-caption" class="font-smaller">
./partials/singles/single-post-article.php:    <h1 id="single-wire-title" class="js-fix-widows"><?php the_title(); ?></h1>
./partials/singles/single-post-article.php:        echo '<a id="single-wire-author" target="_blank" href="https://twitter.com/' . $meta['_cmb_author_twitter'][0] . '">';
./partials/singles/single-post-article.php:    <div id="single-wire-copy" class="text-copy margin-top-basic margin-bottom-basic">
./partials/singles/single-post-article.php:    <div id="single-wire-meta" class="font-smaller">
./partials/singles/single-post-article.php:      <p id="single-wire-publication-date">Published <?php the_time('jS F Y'); ?></p>
./single.php:      get_template_part('partials/singles/single-post-wire');
```

**Comment by varffs** [comment]
hmm I guess I better rename everything :/ problem is working out the article/articles thing. I feel the category should be called article, but in menus and stuff we are probably going to call it articles plural

**Comment by mixcas** [comment]
I don't understand. What's the issue with "Articles"?

**Comment by varffs** [comment]
I think the category could be Article. But often in menus and so on it will be refered to as Articles. And a subheading that says Article is kinda weird. This isn't reflected in this PR as the change of naming is not 100% yet; this edit is partly to see how it looks and feels

**Comment by mixcas** [comment]
I mean, if it will be shown as Articles everywhere what's the problem with naming it that? Why the sub-heading show "article"?

**Comment by varffs** [comment]
The issue is that Article/Audio/Video makes sense but Articles/Audio/Video not so much. But perhaps that is easiest to just call the category articles I'm not sure?

**Comment by mixcas** [comment]
I understand. I think Article/Audio/Video makes sense cuz interwebz and context (blogs) but its up to them. Although having a category named Article could cause confusion. Ex `$article_meta` could be confused with a single post (or post type) instance while it really means the category meta.

**Comment by mixcas** [comment]
I suggest to name the cats in plural and use singular nouns as labels where needed.

**Comment by varffs** [comment]
Yh I think that is probably the best way to do it. Just wish there was a neater way to have 2 names for a cat or something

**Comment by mixcas** [comment]
https://developer.wordpress.org/reference/functions/_n/ ?

**Comment by varffs** [comment]
Yh I know but I don't want to pluralize Audio to Audios so will have to string match to see if the cat is Article[s]

**Comment by mixcas** [comment]
What the problem with my suggestion?

**Comment by varffs** [comment]
What is your suggestion?

**Comment by mixcas** [comment]
Name cats in plural (Audios) and use singular labesl (Audio)

**Comment by varffs** [comment]
Yeah I'm gonna do that

**Comment by mixcas** [comment]
some still appear in

partials/singles/single-post-video.php
lib/renderers.php
front-page.php

**Pull request merged**
